INSERT INTO `c_category` VALUES (1, '瑜伽', 1, '001');
INSERT INTO `c_category` VALUES (2, '托福', 1, '002');
INSERT INTO `c_category` VALUES (3, '健身', 1, '003');
INSERT INTO `c_category` VALUES (4, '音乐', 1, '004');
INSERT INTO `c_category` VALUES (5, '母婴', 1, '005');
INSERT INTO `c_category` VALUES (6, '心理', 1, '006');
INSERT INTO `c_category` VALUES (7, '游泳', 1, '007');
INSERT INTO `c_category` VALUES (8, '公益', 1, '008');
INSERT INTO `c_category` VALUES (9, '其他', 1, '009');
